#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/sourcecode/apollo/node_modules/.pnpm/@graphql-codegen+cli@4.0.1_@babel+core@7.21.4_@types+node@20.2.5_graphql@16.6.0/node_modules/@graphql-codegen/cli/esm/node_modules:/mnt/c/sourcecode/apollo/node_modules/.pnpm/@graphql-codegen+cli@4.0.1_@babel+core@7.21.4_@types+node@20.2.5_graphql@16.6.0/node_modules/@graphql-codegen/cli/node_modules:/mnt/c/sourcecode/apollo/node_modules/.pnpm/@graphql-codegen+cli@4.0.1_@babel+core@7.21.4_@types+node@20.2.5_graphql@16.6.0/node_modules/@graphql-codegen/node_modules:/mnt/c/sourcecode/apollo/node_modules/.pnpm/@graphql-codegen+cli@4.0.1_@babel+core@7.21.4_@types+node@20.2.5_graphql@16.6.0/node_modules:/mnt/c/sourcecode/apollo/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/sourcecode/apollo/node_modules/.pnpm/@graphql-codegen+cli@4.0.1_@babel+core@7.21.4_@types+node@20.2.5_graphql@16.6.0/node_modules/@graphql-codegen/cli/esm/node_modules:/mnt/c/sourcecode/apollo/node_modules/.pnpm/@graphql-codegen+cli@4.0.1_@babel+core@7.21.4_@types+node@20.2.5_graphql@16.6.0/node_modules/@graphql-codegen/cli/node_modules:/mnt/c/sourcecode/apollo/node_modules/.pnpm/@graphql-codegen+cli@4.0.1_@babel+core@7.21.4_@types+node@20.2.5_graphql@16.6.0/node_modules/@graphql-codegen/node_modules:/mnt/c/sourcecode/apollo/node_modules/.pnpm/@graphql-codegen+cli@4.0.1_@babel+core@7.21.4_@types+node@20.2.5_graphql@16.6.0/node_modules:/mnt/c/sourcecode/apollo/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../@graphql-codegen/cli/esm/bin.js" "$@"
else
  exec node  "$basedir/../@graphql-codegen/cli/esm/bin.js" "$@"
fi
