#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/sourcecode/apollo/node_modules/.pnpm/prisma-kysely@1.4.2/node_modules/prisma-kysely/dist/node_modules:/mnt/c/sourcecode/apollo/node_modules/.pnpm/prisma-kysely@1.4.2/node_modules/prisma-kysely/node_modules:/mnt/c/sourcecode/apollo/node_modules/.pnpm/prisma-kysely@1.4.2/node_modules:/mnt/c/sourcecode/apollo/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/sourcecode/apollo/node_modules/.pnpm/prisma-kysely@1.4.2/node_modules/prisma-kysely/dist/node_modules:/mnt/c/sourcecode/apollo/node_modules/.pnpm/prisma-kysely@1.4.2/node_modules/prisma-kysely/node_modules:/mnt/c/sourcecode/apollo/node_modules/.pnpm/prisma-kysely@1.4.2/node_modules:/mnt/c/sourcecode/apollo/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../prisma-kysely/dist/bin.js" "$@"
else
  exec node  "$basedir/../prisma-kysely/dist/bin.js" "$@"
fi
